{
 "title": "Kubernetes / Networking / Retina (Standard) / Pod Traffic",
 "tags": [
  "k8s:retina-network-observability"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod Name",
    "query": {
     "query": "label_values(networkobservability_adv_forward_count,podname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Max Outgoing Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(irate(networkobservability_adv_forward_count{direction=~\"egress\"}[1m]))",
     "legendFormat": "Total PPS"
    },
    {
     "expr": "networkobservability_adv_forward_bytes{podname=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Incoming Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(irate(networkobservability_adv_forward_count{direction=~\"ingress\", namespace!=\"\"}[1m]))",
     "legendFormat": "Total PPS"
    }
   ]
  },
  {
   "title": "Max Outgoing Traffic Bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(irate(networkobservability_adv_forward_bytes{direction=~\"egress\"}[1m]))",
     "legendFormat": "Total PPS"
    }
   ]
  },
  {
   "title": "Max Incoming Traffic Bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(irate(networkobservability_adv_forward_bytes{direction=~\"ingress\", namespace!=\"\"}[1m]))",
     "legendFormat": "Total PPS"
    }
   ]
  },
  {
   "title": "All Outgoing pps per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (podname) (rate(networkobservability_adv_forward_count{\r\n  direction=\"egress\", \r\n  namespace!=\"\"\r\n}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Incoming pps per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (podname) (rate(networkobservability_adv_forward_count{\r\n  direction=\"ingress\", \r\n  namespace!=\"\"\r\n}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Pods Outgoing traffic",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (podname)(irate(networkobservability_adv_forward_count{direction=\"egress\", namespace!=\"\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Pods Incoming traffic",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (podname)(irate(networkobservability_adv_forward_count{direction=\"ingress\", namespace!=\"\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Namespace Outgoing traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (namespace)(irate(networkobservability_adv_forward_count{direction=\"egress\", namespace!=\"\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Namespace Incoming traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (namespace)(irate(networkobservability_adv_forward_count{direction=\"ingress\", namespace!=\"\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Stats | Flag ACK",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (flag)(irate(networkobservability_adv_tcpflags_count{namespace!=\"\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped pps per Destination pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    { "expr": "networkobser", "legendFormat": "__auto" }
   ]
  }
 ]
}