# FROM mcr.microsoft.com/windows/servercore:ltsc2022 As base
FROM mcr.microsoft.com/windows/servercore@sha256:45952938708fbde6ec0b5b94de68bcdec3f8c838be018536b1e9e5bd95e6b943 AS base

# build stages
#COPY ./x64/Release/bpf_event_writer.sys ./bpf_event_writer.sys
#COPY ./x64/Release/event_writer.exe ./event_writer.exe